### PR TITLE
fixes and cleanup

### PR DESCRIPTION
**Pull request by paulczar**
* move etcd.overrides to /etc/default/etcd ( more linuxy, upstart script tries to source that already ).
* template etcd.defaults using values from servers.yml
* provision installs curl if doesn't exist ( I use vbox and my base image doesn't have it )
* provision is now roughly idempotent
* provision starts etcd or restarts it if already running
* gitignore to not save template written .default files
* also listen on 0.0.0.0:4001 as 4001 is the default port for etcdctl.

### CODE REVIEW

**Comment by lowescott** [comment]
Hi Paul, these changes look good. A couple of questions before I merge the PR:

1. I noted some changes to `servers.yml` that will break this setup; specifically, line 16 (which should reference an IP address) now includes a box name.

2. In `etcd.defaults.erb`, I noted that the client URL for etcd to listen on port 4001 (line 10) isn't bound to the value of "priv_ip" from `servers.yml`. We should fix that for consistency.

3. Also in `etcd.defaults.erb`, we haven't coded the ETCD_INITIAL_CLUSTER variable to use the IP addresses provided in `servers.yml` (line 4). Because of the way ERB templates work, this may not be possible; if that's the case, we'll need to update `README.md` with instructions to edit that line with the correct IP addresses if `servers.yml` is modified.

I can go ahead and merge the PR and then fix these issues in a subsequent commit, if that's easiest for you.

**Comment by paulczar** [comment]
I'll address your comments in another commit to the PR later today.

**Comment by paulczar** [comment]
1.  fixed,  that was just me pasting in the wrong place because I'm on virtualbox.

2. it's not bound to priv_ip because etcdctl expects to connect to localhost:4001 by default.  using 0.0.0.0 binds to all interfaces.

3. good catch,  I have templated that as well.

**Comment by paulczar** [comment]
suggest you pull down the branch for the PR and give it a test in case there's some weird difference between virtualbox and vmware providers.

**Comment by lowescott** [comment]
Seems to work fine with the VMware provider, I've merged the PR. Thanks!

**Pull request merged**
